export const lanyardSizes = {

  "1": {
    verticalOffset: -220,
    neckStrapOffset: 1,
    neckStrapWidth: 4.7,
    // neckStrapClip: 9,
    breakawayOffset: 0,
    scale: 1,
    hookWidth: 230,
    hookHeight: 100,
    strapTopOffset: 200,
    cardWidth: 500,
    strapWidth: 60,
    strapHeight: 500,
    connectorHeight: 50,
    connectorTop: 730,
    hookTop: 770,
    cardTop: -80,
    left: { rotate: -20, translateX: "-200px", origin: "top right" },
    right: { rotate: 20, translateX: "142px", origin: "top left" },
  },

  "7/8": {
    verticalOffset: -200,
    neckStrapOffset: 0,
    neckStrapWidth: 5.2,
    breakawayOffset: 0,
    scale: 1,
    hookWidth: 230,
    hookHeight: 120,
    strapTopOffset: 200,
    cardWidth: 500,
    strapWidth: 55,
    strapHeight: 500,
    connectorHeight: 60,
    connectorTop: 720,
    hookTop: 770,
    cardTop: -65,
    left: { rotate: -20, translateX: "-198px", origin: "top right" },
    right: { rotate: 20, translateX: "144px", origin: "top left" },
  },

  "3/4": {
    verticalOffset: -200,
    neckStrapOffset: 1,
    neckStrapWidth: 5.8,
    breakawayOffset: 7,
    scale: 1,
    hookWidth: 230,
    hookHeight: 120,
    strapTopOffset: 200,
    cardWidth: 500,
    strapWidth: 50,
    strapHeight: 500,
    connectorHeight: 50,
    connectorTop: 718,
    hookTop: 760,
    cardTop: -65,
    left: { rotate: -20, translateX: "-195px", origin: "top right" },
    right: { rotate: 20, translateX: "144px", origin: "top left" },
  },

  "5/8": {
    verticalOffset: -200,
    neckStrapOffset: 1,
    neckStrapWidth: 6.6,
    breakawayOffset: 11,
    scale: 1,
    hookWidth: 230,
    hookHeight: 120,
    strapTopOffset: 200,
    cardWidth: 500,
    strapWidth: 45,
    strapHeight: 500,
    connectorHeight: 50,
    connectorTop: 716,
    hookTop: 758,
    cardTop: -70,
    left: { rotate: -20, translateX: "-193px", origin: "top right" },
    right: { rotate: 20, translateX: "148px", origin: "top left" },
  },

  "1/2": {
    verticalOffset: -200,
    neckStrapOffset: 0,
    neckStrapWidth: 7.5,
    breakawayOffset: 15,
    scale: 1,
    hookWidth: 230,
    hookHeight: 120,
    strapTopOffset: 200,
    cardWidth: 500,
    strapWidth: 40,
    strapHeight: 500,
    connectorHeight: 50,
    connectorTop: 714,
    hookTop: 756,
    cardTop: -70,
    left: { rotate: -20, translateX: "-190px", origin: "top right" },
    right: { rotate: 20, translateX: "149px", origin: "top left" },
  },
};